name: Deploy GitHub Pages
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2.1.0
        with:
          node-version: '12.x'

      - name: Install packages
        run: |
          yarn install

      - name: build
        run: |
          yarn run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vuepress/dist
